name: caso2
services:
  back:
    image: back
    container_name: back
    build:
      context: ./back
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./back:/back
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
    ports:
      - 3000:3000
  front:
    image: front
    container_name: front
    build:
      context: ./front
    # tty: true
    command: sh -c "npm install && npm start"
    volumes:
      - ./front/:/front
  base:
    image: base
    container_name: base
    build:
      context: ./base
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5432:5432
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./proxy/myconf.template:/etc/nginx/templates/default.conf.template
      - ./proxy/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - back
