name: caso2
services:
  back:
    image: ${REGISTRY_URL}/back
    container_name: back
    build:
      context: ./back
      target: production
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
  front:
    image: ${REGISTRY_URL}/front
    container_name: front
    build:
      context: ./front
      target: production
  base:
    image: ${REGISTRY_URL}/base
    container_name: base
    build:
      context: ./base
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
  proxy:
    image: nginx:alpine
    container_name: proxy
    environment:
      - FRONT_URL=${FRONT_URL}
    volumes:
      - ./proxy/myconf.production.template:/etc/nginx/templates/default.conf.template
      - ./proxy/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - back
